services:
  postgres:
    image: postgres:16-alpine
    ports:
      - '5482:5432'
    environment:
      POSTGRES_DB: payload_draft_post_poc
      POSTGRES_PASSWORD: payload
      POSTGRES_USER: payload
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U payload -d payload_draft_post_poc']
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
